name: spacy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - scikit-learn=1.2.0
  - nltk
  - spacy
  - tqdm
  - shap
  - geopandas
  - joblib
  - pip
  - pip:
      - aif360==0.6.1
      - natsort

